title: Note AWS
description: This is hub for learning software architect in Amazon Web Services
theme: just-the-docs

url: https://wenyanzhu.github.io/noteaws

mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "11.0.2"

aux_links_new_tab: false
nav_enabled: true
 