title: Note for AWS Architect
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://wenyanzhu.github.io/noteaws

aux_links: # remove if you don't want this link to appear on your pages
  Template Repository: https://github.com/wenyanzhu/noteaws
